### PR TITLE
GPII-2773: Update coverage client.

### PR DESCRIPTION
**Pull request by the-t-in-rtf**
See [GPII-2773](https://issues.gpii.net/browse/GPII-2773) for details.

### CODE REVIEW

**Comment by the-t-in-rtf** [comment]
This is not currently ready for review, in working on the npm@5 spike I noticed problems with the new instrumenter in Windows that I am currently investigating.

**Comment by the-t-in-rtf** [comment]
In researching, it seems like the problems with the new Instrumenter are down to the way in which minimatch explicitly replaces forward slashes in patterns with back slashes.   There are many open issues regarding this, but here's one that seems worth following:

https://github.com/isaacs/minimatch/pull/109

The [node-glob package](https://github.com/isaacs/node-glob) claims to support the pattern we want, i.e. [forward-slashes work correctly cross-platform](https://github.com/isaacs/node-glob#windows).  As the instrumenter only works in node, I will give node-glob a try.

**Comment by the-t-in-rtf** [comment]
I refactored the instrumenter to use node-glob instead of minimatch, it's now confirmed working with Windows (and npm@5).  Ready to review.

**Comment by amb26** [comment]
We really need to get all these other repositories enrolled in CI as well

**Comment by amb26** [comment]
Mysterious test failure now - platform, Windows 7 x64, npm 5.6.0

15:26:02.635:  jq: FAIL: Module "Test the instrumentation functions." Test name "Test content within a nested 'node_modules' directory." - Message: File 'gpii/n
ode_modules/sub-package/index.js' should exist.
15:26:02.637:  jq: Source:     at pok (E:\source\gits\gpii-testem\node_modules\infusion\tests\test-core\jqUnit\js\jqUnit.js:112:15)
    at Object.assertTrue (E:\source\gits\gpii-testem\node_modules\infusion\tests\test-core\jqUnit\js\jqUnit.js:145:13)
    at E:\source\gits\gpii-testem\tests\js\instrumenter-tests.js:40:32
    at Object.fluid.each (E:\source\gits\gpii-testem\node_modules\infusion\src\framework\core\js\Fluid.js:518:17)
    at Array.<anonymous> (E:\source\gits\gpii-testem\tests\js\instrumenter-tests.js:38:27)
    at Object.that.complete (E:\source\gits\gpii-testem\node_modules\infusion\src\framework\core\js\FluidPromises.js:70:25)
    at Object.that.resolve (E:\source\gits\gpii-testem\node_modules\infusion\src\framework\core\js\FluidPromises.js:52:22)
    at Function.fluid.promise.resumeSequence (E:\source\gits\gpii-testem\node_modules\infusion\src\framework\core\js\FluidPromises.js:163:26)
    at Function.fluid.promise.progressSequence (E:\source\gits\gpii-testem\node_modules\infusion\src\framework\core\js\FluidPro .... [output suppressed at 1024
chars - for more output, increase fluid.logObjectRenderChars]
15:26:02.641:  FATAL ERROR: Uncaught exception: ENOENT: no such file or directory, stat 'C:\Users\Bosmon\AppData\Local\Temp\instrumenter-tests-16tiklbg-42\with-
node-modules\gpii\node_modules\sub-package\index.js'
Error: ENOENT: no such file or directory, stat 'C:\Users\Bosmon\AppData\Local\Temp\instrumenter-tests-16tiklbg-42\with-node-modules\gpii\node_modules\sub-packag
e\index.js'
    at Object.fs.statSync (fs.js:948:11)

**Comment by the-t-in-rtf** [comment]
So, I've run repeated runs in the Windows 10 VM with node 8.9.4 and npm 5.6.0 with no issues.  I'm not sure the Windows 7 VM is still viable, but I will at least try that.  In the mean time, I'll have to rely on your experience running the tests.

The error itself suggests that that instrumentation function did not produce any output.  Is this the only error?  Is it consistently failing?

**Comment by amb26** [comment]
I got the same result with multiple versions of node in my physical machine, as well as in our standard Windows vagrant box based on Windows 10 and the npm 3.x ecosystem

**Comment by the-t-in-rtf** [comment]
As we've discussed in chat, I think the problem gets down the underlying filesystem, which in my case is the host FS mounted as a network drive.  I will need to reboot into windows running on bare iron to confirm.

**Comment by the-t-in-rtf** [comment]
OK, after further discussions, it became clear that I could always run the tests in Windows 7 or 10 from v: (the network drive mounting the host share).  Cloning the source to a non-network mount point such as `c:/users/vagrant` immediately lets me see the problem.  I will continue investigating and report back.

**Comment by the-t-in-rtf** [comment]
OK, I figured it out.  Thankfully all of my various theories about filesystems, path separators, windows-specific bugs in various libraries turned out to be wild speculation.  The answer was much much simpler.

My use of `node_modules` in `.gitignore` was also screening "deep" content, like the content I use to test handling of `node_modules` directories as we use them in universal.  The files were never checked in, and anyone actually checking out the branch would see failures to instrument because the code to be instrumented didn't exist.  It always worked for me in Vagrant because my specific directory had the unchecked-in content.

Based on how we handled this in universal, I updated that ignore to use `/node_modules/` and checked in the missing content.  I can confirm that the tests now pass with a newly-checked-out instance of the branch in a VM.  This should be ready for review again.

**Comment by the-t-in-rtf** [comment]
I manually created a git tag for the release, added release notes, and updated the forward-facing version in master.

**Comment by amb26** [comment]
Sorry to have jumped the gun on this :( It appears that it is still bound, via the gpii-launcher dependency, to an ancient version of kettle

**Pull request merged**
