### PR TITLE
GPII-3278: Add "safe rollup" mechanism.

### PR DESCRIPTION
**Pull request by the-t-in-rtf**
See [GPII-3278](http://issues.gpii.net/browse/GPII-3278) for details..

### CODE REVIEW

**Comment by amb26** [comment]
A variety of intermittent test failures on Windows.

On my first run:
````
23:43:12.116:  jq: Test concluded - Module "Testing coverage detection and reporting..." Test name "Running a suite of tests without test co
verage...": 4/4 passed - PASS
23:53:20.325:  TESTEM ERROR:{
    "killed": false,
    "code": 1,
    "signal": null,
    "cmd": "node ../../node_modules/testem/testem.js ci --file ../testem-fixtures/coverage-fixtures/testem-package-relative-paths.js"
}
23:53:20.332:  jq: FAIL: Module "Testing coverage detection and reporting..." Test name "Running a suite of tests with package-relative path
s..." - Message: There should be no errors running testem...
23:53:20.335:  jq: Source:     at pok (E:\Source\gits\gpii-testem\node_modules\infusion\tests\test-core\jqUnit\js\jqUnit.js:112:15)
    at Object.fail (E:\Source\gits\gpii-testem\node_modules\infusion\tests\test-core\jqUnit\js\jqUnit.js:129:13)
    at E:\Source\gits\gpii-testem\tests\js\testem-component-functional-tests.js:37:24
    at ChildProcess.exithandler (child_process.js:282:5)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
23:53:20.351:  jq: FAIL: Module "Testing coverage detection and reporting..." Test name "Running a suite of tests with package-relative path
s..." - Message: The coverage should be as expected...
23:53:20.352:  jq: Expected: {
    "branches": {
        "total": 2,
        "covered": 2,
        "skipped": 0,
        "pct": 100
    }
}
23:53:20.363:  jq: Actual: {
    "branches": {
        "total": 0,
        "covered": 0,
        "skipped": 0,
        "pct": "Unknown"
    }
}
23:53:20.373:  jq: Source:     at Object.assertDeepEq (E:\Source\gits\gpii-testem\node_modules\infusion\tests\test-core\jqUnit\js\jqUnit.js:
180:23)
    at Object.jqUnit.assertLeftHand (E:\Source\gits\gpii-testem\node_modules\infusion\tests\test-core\jqUnit\js\jqUnit.js:256:16)
    at E:\Source\gits\gpii-testem\tests\js\testem-component-functional-tests.js:58:32
    at ChildProcess.exithandler (child_process.js:282:5)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
23:53:20.385:  Removing dir 'E:/Source/gits/gpii-testem/tests/testem-fixtures/coverage-fixtures/reports'...
23:53:20.391:  Removing dir 'E:/Source/gits/gpii-testem/tests/testem-fixtures/coverage-fixtures/coverage'...
23:53:20.392:  Removed reports and coverage from this test run...
23:53:20.405:  jq: Test concluded - Module "Testing coverage detection and reporting..." Test name "Running a suite of tests with package-relative paths...": 4/6 passed - FAIL
````

On my second run, they jammed at 
````
00:00:49.643:  jq: Test concluded - Module "Testing coverage detection and reporting..." Test name "Running a suite of tests without test coverage...": 4/4 passed - PASS
````

Chrome was left open showing the URL `http://localhost:7357/116398575453007/complete.html` for which the returned content was "403 Forbidden"

On my third run, I got the same result as the 2nd run. Closing the Chrome browser does not cause the test run to restart.

**Comment by the-t-in-rtf** [comment]
@amb26, I see similar errors in a Windows VM.  Investigating now.

**Comment by the-t-in-rtf** [comment]
It looks like this is down to using a package-relative value for the current working directory.  `fluid.module.resolvePath("%package-relative")` results in a `cwd` value of `V:/tests/testem-fixtures/coverage-fixtures` (note forward slashes).

If I hard-code that option to `V:\\tests\\testem-fixtures\\coverage-fixtures`, the tests pass without problems.  I will read through the Testem docs and look at the code behind fluid.module.resolvePath to see what our best option is for addressing this.

**Comment by the-t-in-rtf** [comment]
Here's the logic that decides whether to send the 403 error, I'll try it out with the debugger shortly:

https://github.com/testem/testem/blob/951500926010f31d59e635fbee508461deabf207/lib/server/index.js#L340

We may be able to bypass the check by allowing "unsafe" paths, I'll test that as well.

**Comment by the-t-in-rtf** [comment]
OK, I know what's happening and why and will write up a ticket against Testem.  Hopefully they'll accept a pull to fix it, it's like a ten character change.

**Comment by the-t-in-rtf** [comment]
OK, I confirmed that my fix solves the problem, but rather than monkey-patch testem, I'll put in a ticket with them and leave a workaround in place with a note.

**Comment by the-t-in-rtf** [comment]
@amb26 the workaround is in, you should be able to run the tests now.

**Comment by the-t-in-rtf** [comment]
@amb26, the Testem team was incredibly responsive and already merged my work and cut a release.  I have updated this pull to remove the workaround and confirmed the tests passing in Windows.

**Comment by amb26** [comment]
Thanks, this now works great, @the-t-in-rtf . Should you ever find yourself at a loose end, it turns out that the inner function on line 106 of instrumenter.js, " return inverseWithExclamation.substring(1);" is never hit during coverage : P

**Comment by the-t-in-rtf** [comment]
Thanks, I have cut the release, added release notes on GitHub, and updated the forward-facing version in master.

It's good that you pointed out that particular coverage gap, I quickly whipped up a test to hit that branch, and discovered that negated exclusions don't actually work at the moment.  It's a bit much to fix today, but I created [GPII-3300](https://issues.gpii.net/browse/GPII-3300) and will keep thinking about it, as it's the kind of inherited limitation I don't like living with.

**Pull request merged**
